# Generated by Django 4.1.2 on 2022-10-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_descripcion', models.CharField(max_length=255, verbose_name='Nombre y descripción')),
                ('proveedor', models.CharField(max_length=255, verbose_name='Proveedor')),
                ('direccion_proveedor', models.CharField(max_length=255, verbose_name='Dirección del proveedor')),
                ('numero_proveedor', models.CharField(max_length=255, verbose_name='Número del contacto del proveedor')),
                ('fecha_modificacion', models.DateField(max_length=20, verbose_name='Fecha de modificación')),
                ('fecha_vencimiento', models.DateField(max_length=20, verbose_name='Fecha de vencimiento')),
                ('categoria_producto', models.CharField(max_length=100, verbose_name='Categoria del producto')),
                ('cantidad_productos', models.IntegerField(verbose_name='Cantidad actual')),
                ('stock_maximo', models.IntegerField(verbose_name='Stock minima')),
                ('stock_minimo', models.IntegerField(verbose_name='Stock maxima')),
                ('unidades', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Información',
            },
        ),
    ]
