# Generated by Django 4.1.2 on 2022-11-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='categoria_producto',
            field=models.CharField(choices=[('1', 'Alimentos'), ('2', 'Bebidas'), ('3', 'Limpieza'), ('4', 'Otros')], max_length=100, verbose_name='Categoria del producto'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='unidades',
            field=models.CharField(choices=[('1', 'Kg'), ('2', 'L'), ('3', 'Unidades'), ('4', 'Otros')], max_length=255, verbose_name='Unidades'),
        ),
    ]
