# Generated by Django 4.1.2 on 2023-05-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_proveedores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria_producto',
            field=models.CharField(choices=[('1', 'Alimentos y Bebidas'), ('2', 'Productos de limpieza'), ('3', 'Papeleria'), ('4', 'Salud'), ('5', 'Otros')], max_length=100, verbose_name='Categoria del producto'),
        ),
    ]
