# Generated by Django 4.1.2 on 2023-05-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_producto_categoria_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='Usuario')),
                ('model', models.CharField(max_length=255, verbose_name='Modelo')),
                ('accion', models.CharField(max_length=255, verbose_name='Acción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
            ],
            options={
                'verbose_name_plural': 'Auditoria',
            },
        ),
    ]
