# Generated by Django 4.1.2 on 2023-05-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auditoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacion',
            name='direccion_proveedor',
        ),
        migrations.RemoveField(
            model_name='informacion',
            name='numero_proveedor',
        ),
    ]
