# Generated by Django 4.1.2 on 2023-05-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_informacion_direccion_proveedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaEntradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(max_length=255, verbose_name='Responsable')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('producto', models.CharField(max_length=255, verbose_name='Producto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('razon', models.CharField(max_length=255, verbose_name='Razón')),
                ('detalles', models.CharField(max_length=255, verbose_name='Detalles')),
            ],
            options={
                'verbose_name_plural': 'Auditoria',
            },
        ),
        migrations.DeleteModel(
            name='Auditoria',
        ),
    ]
