# Generated by Django 4.1.2 on 2023-05-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auditoriaentradas_delete_auditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaSalidas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('responsable', models.CharField(max_length=255, verbose_name='Responsable')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('producto', models.CharField(max_length=255, verbose_name='Producto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('razon', models.CharField(max_length=255, verbose_name='Razón')),
                ('proveedor', models.CharField(max_length=255, verbose_name='Proveedor')),
            ],
            options={
                'verbose_name_plural': 'Auditoria',
            },
        ),
        migrations.RemoveField(
            model_name='auditoriaentradas',
            name='detalles',
        ),
        migrations.RemoveField(
            model_name='auditoriaentradas',
            name='razon',
        ),
        migrations.AddField(
            model_name='auditoriaentradas',
            name='proveedor',
            field=models.CharField(default='', max_length=255, verbose_name='Proveedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditoriaentradas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
