# Generated by Django 4.1.2 on 2023-05-27 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auditoriasalidas_remove_auditoriaentradas_detalles_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuditoriaEntradas',
            new_name='AuditoriaEntrada',
        ),
    ]
